/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.hachikuu.autogfncloudgg;

public class App {
    public static void main(String[] args) {
        AppThread thread = new AppThread();
        thread.init();
        thread.run();
    }
}
